services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}

  # Apache License v2.0, January 2004
  # Courtesy of the CNCF project, Jaeger @ https://github.com/jaegertracing/jaeger
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false  # Disable security features
      - xpack.security.http.ssl.enabled=false  # Disable HTTPS
      - action.destructive_requires_name=false
      - xpack.monitoring.collection.enabled=false  # Disable monitoring features
    ports:
      - "9200:9200"
  # End Apache License v2.0

volumes:
  boilerplate-db:
